project/project/urls.py
from django.contrib import admin
from django.urls import path, include

from simpleapp import views
from simpleapp.views import multiply, Index

urlpatterns = [
   path('i18n/', include('django.conf.urls.i18n')),  # подключаем встроенные эндопинты для работы с локализацией # noqa
   path('', views.Start_Padge, name='Start'),
   path('admin/', admin.site.urls),
   path('product/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('products/', include('simpleapp.urls')),
   path('index/', Index.as_view(), name='index'),  # страница с Hello world
   path('multiply/', multiply),  # для выполнения логики, связанной с умножением, при обращении пользователя по пути "multiply/" # noqa
   # Добавим urls приложения, с которым ранее работали в этом модуле — “django.contrib.auth”. # noqa
   # Django скажет, как обрабатывать запросы от пользователей по ссылкам, которые начинаются с /accounts/. # noqa
   # path('accounts/', include('django.contrib.auth.urls')),
   # path("accounts/", include("accounts.urls")),  # подключим urls приложения accounts # noqa
   path('accounts/', include('allauth.urls')),  # Оставили только allauth
]

project/simpleapp/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.urls import reverse
from django.contrib.auth.models import User
from django.core.cache import cache
from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy

# специальная функция reverse, которая позволяет нам указывать
# не путь вида /products/…, а название пути.


# Товар для нашей витрины
class Product(models.Model):
    name = models.CharField(
        max_length=50,
        unique=True,  # названия товаров не должны повторяться
    )
    price = models.FloatField(validators=[MinValueValidator(0.0)],)
    # price = models.FloatField(validators=[MinValueValidator(0.0, 'Price should be >= 0.0')])
    quantity = models.IntegerField(validators=[MinValueValidator(0)],)
    # quantity = models.IntegerField(validators=[MinValueValidator(0, 'Quantity should be >= 0')])
    # поле категории будет ссылаться на модель категории
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='products',  # все продукты в категории будут доступны через поле products
        verbose_name=pgettext_lazy('help text for Product model', 'This is the help text'),
    )
    # category = models.ForeignKey('Category', on_delete=models.CASCADE)
    description = models.TextField()

    def __str__(self):
        return f'{self.name.title()}: {self.description[:10]} ({self.price})'

    # Django не знает, какую страницу нужно открыть после создания товара.
    # Мы можем убрать проблему, добавив метод get_absolute_url в модель.
    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.id)])

    # def get_absolute_url(self):
    #     # добавим абсолютный путь, чтобы после создания нас перебрасывало на
    #     страницу с товаром
    #     return f'/products/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'product-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его


# Категория, к которой будет привязываться товар
class Category(models.Model):
    # названия категорий тоже не должны повторяться
    # name = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=100, unique=True, help_text=_('category name'))
    # добавим переводящийся текст подсказку к полю

    def __str__(self):
        return self.name.title()


class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

project/templates/index.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Index
{% endblock title %}

{% block content %}

<!--{% load i18n %} &lt;!&ndash; Загружаем теги с переводами, без этой строки ничего не будет работать &ndash;&gt;-->

<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Page title</title>-->
<!--</head>-->
<!--<body>-->
<!--    {{ string }} &lt;!&ndash; Это уже знакомая нам переменная, просто засунули её в шаблон &ndash;&gt;-->
<!--    {% trans "Check out my new cool translation" %}! &lt;!&ndash; Переводим строку &ndash;&gt;-->
<!--</body>-->
<!--</html>-->


<!--  -->

<!--{% load i18n %}-->

<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Page title</title>-->
<!--</head>-->
<!--<body>-->
<!--    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} &lt;!&ndash; Не забываем по csrf_token для POST запросов &ndash;&gt;-->
<!--        <input type="hidden" name="next" value="{{ redirect_to }}">-->
<!--        {% get_current_language as LANGUAGE_CODE %}-->
<!--        <select name="language" id="">-->
<!--            {% get_available_languages as LANGUAGES %} &lt;!&ndash; получаем языки &ndash;&gt;-->
<!--            {% get_language_info_list for LANGUAGES as languages %} &lt;!&ndash; Помещаем их в список languages &ndash;&gt;-->

<!--            {% for language in languages %} &lt;!&ndash; Итерируясь по списку, выводим их название на языке пользователя и код &ndash;&gt;-->
<!--                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %}>-->
<!--                    {{ language.name_local }} - {{ language.code }}-->
<!--                </option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--        <input type="submit" value="set">-->
<!--    </form>-->

<!--    {{ string }} &lt;!&ndash; Это уже знакомая нам переменная, просто засунули её в шаблон &ndash;&gt;-->
<!--    {% trans "Check out my new cool translation" %}! &lt;!&ndash; Переводим строку &ndash;&gt;-->
<!--</body>-->
<!--</html>-->


<!-- Перевод локализация -->

<!--{% load i18n %}-->

<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Page title</title>-->
<!--</head>-->
<!--<body>-->
<!--    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} &lt;!&ndash; Не забываем по csrf_token для POST-запросов &ndash;&gt;-->
<!--        <input type="hidden" name="next" value="{{ redirect_to }}">-->

<!--        <select name="language" id="">-->
<!--            {% get_available_languages as LANGUAGES %} &lt;!&ndash; получаем языки &ndash;&gt;-->
<!--            {% get_language_info_list for LANGUAGES as languages %} &lt;!&ndash; Помещаем их в список languages &ndash;&gt;-->

<!--            {% for language in languages %} &lt;!&ndash; Итерируясь по списку, выводим их название на языке пользователя и код &ndash;&gt;-->
<!--                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >-->
<!--                    {{ language.name_local }} - {{ language.code }}-->
<!--                </option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--        <input type="submit" value="set">-->
<!--    </form>-->

<!--    {% for model in models %}-->
<!--    <div class="model-class">-->
<!--        {{ model.name }}-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--</body>-->
<!--</html>-->


<!-- часовые пояса -->

<!--{% load i18n %}-->
<!--{% load tz %} &lt;!&ndash; не забываем загрузить тег для работы с часовыми поясами &ndash;&gt;-->

<!--<html lang="en">-->
<!--<head>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta http-equiv="X-UA-Compatible" content="IE=edge">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <title>Page title</title>-->
<!--</head>-->
<!--<body>-->

<!--    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} &lt;!&ndash; Не забываем по csrf_token для POST запросов &ndash;&gt;-->
<!--        <input type="hidden" name="next" value="{{ redirect_to }}">-->

<!--        <select name="language" id="">-->
<!--            {% get_available_languages as LANGUAGES %} &lt;!&ndash; получаем языки &ndash;&gt;-->
<!--            {% get_language_info_list for LANGUAGES as languages %} &lt;!&ndash; Помещаем их в список languages &ndash;&gt;-->

<!--            {% for language in languages %} &lt;!&ndash; Итерируясь по списку, выводим их название на языке пользователя и код &ndash;&gt;-->
<!--                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected {% endif %} >-->
<!--                    {{ language.name_local }} - {{ language.code }}-->
<!--                </option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--        <input type="submit" value="set">-->
<!--    </form>-->

<!--    {% get_current_timezone as TIME_ZONE %}-->
<!--    <form action="" method="POST">-->
<!--        {% csrf_token %}-->
<!--        <label for="timezone">Time zone:</label>-->
<!--        <select name="timezone">-->
<!--            {% for tz in timezones %}-->
<!--            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>-->
<!--            {% endfor %}-->
<!--        </select>-->
<!--        <input type="submit" value="Set">-->
<!--    </form>-->

<!--    {{ TIME_ZONE }}-->
<!--    {{ current_time|timezone:TIME_ZONE }} &lt;!&ndash; Отображаем время в выбранном часовом поясе  &ndash;&gt;-->

<!--    {% for model in models %}-->
<!--    <div class="model-class">-->
<!--        {{ model.name }}-->
<!--    </div>-->
<!--    {% endfor %}-->
<!--</body>-->
<!--</html>-->


<!-- Тёмная тема от времени у нас будет меняться оформление сайта -->

{% load i18n %}
{% load tz %} <!-- не забываем загрузить тег для работы с часовыми поясами -->


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Page title</title>
    <!-- Если сейчас больше чем 19 или же меньше 7, то выводим тёмную тему, иначе выводим светлую -->
    <style>
        body {background-color: {% if current_time.hour >= 19 or current_time.hour <= 7 %} darkcyan {% else %} powderblue {% endif %};}
    </style>
</head>
<body>

    <form action="{% url 'set_language' %}" method="POST"> {% csrf_token %} <!-- Не забываем по csrf_token для POST-запросов -->
        <input type="hidden" name="next" value="{{ redirect_to }}">

        <select name="language" id="">
            {% get_available_languages as LANGUAGES %} <!-- получаем языки -->
            {% get_language_info_list for LANGUAGES as languages %} <!-- Помещаем их в список languages -->

            {% for language in languages %} <!-- Итерируясь по списку, выводим их название на языке пользователя и код -->
                <option value="{{ language.code }}" {% if language.code == LANGUAGE_CODE %} selected >{% endif %} >
                    {{ language.name_local }} - {{ language.code }}
                </option>
            {% endfor %}
        </select>
        <input type="submit" value="set">
    </form>

    {% get_current_timezone as TIME_ZONE %}
    <form action="" method="POST">
        {% csrf_token %}
        <label for="timezone">Time zone:</label>
        <select name="timezone">
            {% for tz in timezones %}
            <option value="{{ tz }}"{% if tz == TIME_ZONE %} selected{% endif %}>{{ tz }}</option>
            {% endfor %}
        </select>
        <input type="submit" value="Set">
    </form>

    {{ TIME_ZONE }}
    {{ current_time|timezone:TIME_ZONE }} <!-- Отображаем время в выбранном часовом поясе  -->

    {% for model in models %}
    <div class="model-class">
        {{ model.name }}
    </div>
    {% endfor %}


</body>
</html>
{% endblock content %}

project/templates/product.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% block title %}
Product
{% endblock title %}

{% block content %}
<h1>{{ product }}</h1>
<hr>
<p>{{ product.description }}</p>
<hr>
    <td>
        {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
        {% if perms.simpleapp.change_product %}
        <hr>
        <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
        {% endif %}
        {% if perms.simpleapp.delete_product %}
        <hr>
        <a href="{% url 'product_delete' product.id %}">Удалить</a>
        {% endif %}
    </td>
{% endblock content %}

project/templates/product_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление товара</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.name }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

project/templates/product_edit.html
{% extends 'flatpages/default.html'%}

{% block content %}
<h1>Товар</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

project/templates/products.html
{% extends 'flatpages/default.html' %}
<!-- Подключаем новый файл с нашим тегом -->
{% load custom_filters %}
<!-- Импортируем модуль с нашим тегом -->
{% load custom_tags %}

{% block title %}
Products
{% endblock title %}

{% block content %}
    <h1>Все товары</h1>
    <h3>{{ time_now|date:'M d Y' }}</h3>
    <!-- Если в переменной next_sale будет None,
    то выведется указанный в фильтре текст -->
    <h3> {{ next_sale|default_if_none:"Чуть позже сообщим о распродаже!" }}
    </h3>
<!--     Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе -->
    <!-- автоматическая генерация HTML-кода формы -->
    <form action="" method="get">
        <!-- Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями -->
        {{ filterset.form.as_p }}
        <!--Добавим кнопку отправки данных формы -->
        <input type="submit" value="Найти" />
    </form>

<!--    <form action="" method="get" >-->
<!--        {{ filterset.form.non_field_errors }}  &lt;!&ndash; вывели все ошибки, не относящиеся к полям формы &ndash;&gt;-->

<!--        {{ filterset.form.name__icontains.errors }}  &lt;!&ndash; ошибки, которые относятся к полю поиска по названию товара &ndash;&gt;-->
<!--        &lt;!&ndash; составляем сами заголовки (label) и поля ввода данных формы (input) &ndash;&gt;-->
<!--        <label for="{{ filterset.form.name__icontains.id_for_label }}">Search</label>-->
<!--        <input-->
<!--            id="{{ filterset.form.name__icontains.id }}"-->
<!--            name="{{ filterset.form.name__icontains.name }}"-->
<!--            value="{{ filterset.form.name__icontains.value }}"-->
<!--            class="form-control"-->
<!--        >-->
<!--        <input type="submit" class="mt-3 btn-primary" value="Найти" />-->
<!--    </form>-->
    <hr>
    {# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.simpleapp.add_product %}
    <a href="{% url 'product_create' %}">Добавить товар</a>
    {% endif %}

    {% if products %}
        <table  style="margin-left: auto; margin-right: auto;" border="3" cellspacing="7" cellpadding="7">
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Категория</td>
               <td>Цена</td>
               <td>Количество</td>
           </tr>

           {% for product in products %}
           <tr>
               <td><a href="{% url 'product_detail' product.pk %}">{{ product.name }}</a></td>
               <!-- Добавим специальный фильтр truncatechars,
                чтобы ограничить количество символов до 15.
                Все остальные символы превратятся в многоточие. -->
               <td>{{ product.description|truncatechars:15 }}</td>
               <td>{{ product.category.name }}</td>
               <!-- Используем наш фильтр -->
               <td>{{ product.price|currency }}</td>
               <td>{{ product.quantity }}</td>
               <td>
                    {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}
                    {% if perms.simpleapp.change_product %}
                    <a href="{% url 'product_update' pk=product.id %}">Изменить</a>
                    {% endif %}
                    {% if perms.simpleapp.delete_product %}
                    <a href="{% url 'product_delete' product.id %}">Удалить</a>
                    {% endif %}
                </td>
           </tr>
           {% endfor %}
        </table>
    {% else %}
        <h2>Товаров нет!</h2>
    {% endif %}

    <!-- Добавляем пагинацию на страницу -->

    <!-- Информация о предыдущих страницах -->
    {% if page_obj.has_previous %}
    <!-- Для каждой ссылки пагинации указываем обработку через новый тег -->
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {# Информация о текущей странице #}
    {{ page_obj.number }}

    {# Информация о следующих страницах #}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

project/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}